GET http://localhost:3333/users
###
POST http://localhost:3333/users
content-type: application/json

{
  "name": "Gabriel",
  "email": "gabriel@example.com"
}

###
DELETE http://localhost:3333/users/b8f2dbb7-932b-47f0-b4e1-40a6f5bbb68b